Back 800 update configuration
LedgerHQ/ledger-wallet-daemon pull request #258
Opened 2020-08-04 22:57 UTC by RomanWlm

Refresh configuration of WD
- Explorer STG V3 
- update_wallet_config is not an option anymore (reload at startup)

2020-11-16 10:48 UTC, mbasire-ledger requested changes

2020-11-16 10:54 UTC, mbasire-ledger approved these changes

2020-11-16 10:54 UTC, mbasire-ledger commented on src/it/resources/application.conf
> +        host = "https//etc.explorers.vault.ovh.ppr.ldg-tech.com"
`host = "https://etc.explorers.vault.ovh.ppr.ldg-tech.com"`

2020-11-19 10:18 UTC, RomanWlm commented on src/it/resources/application.conf
> +        port = 80
```suggestion
        port = 443
```

2020-11-19 10:18 UTC, RomanWlm commented on wd-local.env
> +
```suggestion
```

2020-11-20 09:46 UTC, RomanWlm commented on src/main/resources/application.conf.sample
>          explorer_version = "v2"
```suggestion
        explorer_version = "v3"
```

2020-11-20 11:35 UTC, dud225 reviewed
I fully support tthis endeavour :+1: 
I've 2 comments:
- We may need to configure the WD to point to a different explorer endpoint for all coins (eg to test a new infrastructure). There are a lot of coins, we may miss some of them. We would need to be able to overwrite the default settings.
- There may always be a gap between the coins defined within the WD and coins coming in on the Vault. Many coins have similarities with existings ones eg BTC, so it would be great to be able to dynamically add new coin settings in some way.

2020-11-21 13:50 UTC, merged