Back 1012 datadog agent with jdk8 upgrade
LedgerHQ/ledger-wallet-daemon pull request #282
Opened 2020-10-30 10:07 UTC by mbasire-ledger

In order to monitor the behavior of the wallet daemon, the datadog jvm agent has been attached.

2020-11-02 10:57 UTC, RomanWlm approved these changes

2020-11-02 10:57 UTC, RomanWlm commented on Dockerfile
> +ENV DD_VERSION=2.9.0-rc4
We will need to automate this, otherwise we will miss to update it frequently 👀

2020-11-02 11:00 UTC, RomanWlm commented
Goss validation is still failing, we should try to run locally docker images in order to access to logs

2020-11-02 11:00 UTC, RomanWlm requested changes
HODL as goss validation is not working properly

2020-11-10 17:17 UTC, mbasire-ledger commented on Dockerfile
> +ENV DD_VERSION=2.9.0-rc4
DD_VERSION has been set to COMMIT_HASH.

By the way, DD_SERVICE should not be changed. What other value may it contain ?

2020-11-12 14:02 UTC, YBadiss commented on Dockerfile
> +ENV DD_PROFILING_ENABLED=false
why do you disable them all?

2020-11-12 14:46 UTC, mbasire-ledger commented on Dockerfile
> +ENV DD_PROFILING_ENABLED=false
I disabled all of them because of image testing step in CI.
I was thinking that disabled by default was not a bad thing.
I hoped datadog would be activated at deployment. 
What do you think about this ?

2020-11-17 08:12 UTC, mbasire-ledger commented on Dockerfile
> +ENV DD_VERSION=2.9.0-rc4
DD_VERSION get the DOCKER_TAG at image building step. It can  be overriden at deployment time.

2020-11-21 13:58 UTC, RomanWlm approved these changes

2020-11-24 10:19 UTC, vbergeron-ledger approved these changes

2020-12-02 08:51 UTC, mbasire-ledger commented
It seems datadog has been integrated in another PR. Maybe we should close this one ?

2020-12-02 09:30 UTC, closed without merging