BACK-1079 WIP AccountSynchronizer becomes an Actor
LedgerHQ/ledger-wallet-daemon pull request #285
Opened 2020-11-04 07:49 UTC by mbasire-ledger

AccountSynchronizer does not block its thread anymore.
TODO: At the end of a sync, the event is not sent to the publisher
TODO: Resync action not implemented yet

2020-11-06 13:18 UTC, RomanWlm requested changes
HODL for CI pass

2020-11-06 13:18 UTC, RomanWlm commented on src/main/scala/co/ledger/wallet/daemon/services/AccountSynchronizer.scala
> +      Try(Await.result(status, 10 seconds)).toOption
Finally we use Await here ?

2020-11-09 17:43 UTC, mbasire-ledger commented on src/main/scala/co/ledger/wallet/daemon/services/AccountSynchronizer.scala
> +      Try(Await.result(status, 10 seconds)).toOption
This method was already awaiting for a result. We should change the result to a Future of something in a next release.

2020-11-09 18:10 UTC, RomanWlm approved these changes

2020-11-09 18:10 UTC, merged