LWD/PubKey Authentication removal
LedgerHQ/ledger-wallet-daemon pull request #290
Opened 2020-11-16 07:54 UTC by RomanWlm

Remove Authentication and User entity
WalletPool Instances are cached, several WalletPool instances trigger libcore crashes.

2020-11-16 14:41 UTC, mbasire-ledger requested changes
CI Integration tests do not pass.

2020-11-16 14:41 UTC, mbasire-ledger commented on src/it/scala/co/ledger/wallet/daemon/utils/APIFeatureTest.scala
> +  def defaultHeaders: Map[String, String] = Map.empty
It should be a val. BTW, is `headers` parameter mandatory ?

2020-11-17 17:22 UTC, RomanWlm commented on src/main/scala/co/ledger/wallet/daemon/database/DBMigrations.scala
> +    0 -> (pools.schema ++ databaseVersions.schema).create
No I tested on a existing db it works, the reverse doesnot

2020-11-17 17:23 UTC, RomanWlm commented on src/it/scala/co/ledger/wallet/daemon/utils/APIFeatureTest.scala
> +  def defaultHeaders: Map[String, String] = Map.empty
No, just a safe shortcut that could be removed IMO

2020-11-21 17:49 UTC, merged