BACK 1119 Return to idle state on failure and schedule a sync
LedgerHQ/ledger-wallet-daemon pull request #297
Opened 2020-11-18 21:54 UTC by mbasire-ledger

The account synchronizer replies only on ForceSynchronization and GetStatus.
All known messages are handled in each state.

On error: return to idle state and schedule a sync

2020-11-18 22:38 UTC, RomanWlm requested changes
Few comments inline. 
As I understand we need now to reschedule manually the next sync. 
Let's discuss about the PR together 👍

2020-11-18 22:38 UTC, RomanWlm commented on src/main/scala/co/ledger/wallet/daemon/services/AccountSynchronizer.scala
> +    case StartSynchronization =>
Add comment to explain that we do not expect any processing

2020-11-18 22:38 UTC, RomanWlm commented on src/main/scala/co/ledger/wallet/daemon/services/AccountSynchronizer.scala
> +    case StartSynchronization =>
Same here :)

2020-11-19 08:00 UTC, mbasire-ledger commented
> Few comments inline.
> As I understand we need now to reschedule manually the next sync.
> Let's discuss about the PR together

This is not really mandatory but it is safe to reschedule. The eventual previous scheduled StartSynchronization is cancelled. 
StartSynchronization was still unscheduled while handling ReSync command (wiping account operations data).

Let me remind you that the timer's delay is actually short by default. ie, after the end of a sync or a failure, the AccountSynchronizer will wait $SYNC_INTERVAL_IN_SECONDS (default : 1 minute) before retry a sync.

It means is **not** really **periodic** but automatic. The real problem : an account synchronizer can not be stopped. It has to be killed by its manager (a future feature maybe ?).

2020-11-19 10:16 UTC, RomanWlm approved these changes
Pon Poulot

2020-11-19 10:16 UTC, merged