BACK-1316 - user pref redis support (Backport 2.8.x)
LedgerHQ/ledger-wallet-daemon pull request #326
Opened 2020-12-31 15:52 UTC by RomanWlm

2021-01-04 08:37 UTC, mbasire-ledger commented on docker-compose.yml
> +    build: .
Good choice

2021-01-04 08:43 UTC, mbasire-ledger commented on src/main/scala/co/ledger/wallet/daemon/database/RedisPreferenceBackend.scala
> +  private implicit val akkaSystem: ActorSystem = akka.actor.ActorSystem()
It should be injected. don't you think ?

2021-01-04 08:58 UTC, mbasire-ledger commented on src/main/scala/co/ledger/wallet/daemon/database/RedisPreferenceBackend.scala
> +    prefCache.get(ByteBuffer.wrap(bytes)).map(_.array).orNull
Do libcore expect a null when nothing has been found ? The `get()` signature let me think not.

2021-01-04 09:33 UTC, mbasire-ledger requested changes
https://github.com/debasishg/scala-redis gives a scala redis client **sync** which should suit our needs. 
The PreferencesBackend expect **sync** responses.

2021-01-04 10:04 UTC, twilgenbus-ledger commented on src/main/scala/co/ledger/wallet/daemon/database/RedisPreferenceBackend.scala
> +    prefCache.get(ByteBuffer.wrap(bytes)).map(_.array).orNull
This line was directly copied from the [`PostgresPreferenceBackend`](https://github.com/LedgerHQ/ledger-wallet-daemon/blob/f39402c03c9c91247e3ae15549ff6915ca11b490/src/main/scala/co/ledger/wallet/daemon/database/PostgresPreferenceBackend.scala#L45).

2021-01-04 14:15 UTC, twilgenbus-ledger commented
@mbasire-ledger It has been re-implemented with the proposed library.

2021-01-04 14:34 UTC, mbasire-ledger commented on src/main/scala/co/ledger/wallet/daemon/models/Pool.scala
> +          dbPrefix <- Try(config.getString("postgres.core.db_name_prefix"))
This is not the good key on 2.8

2021-01-04 14:39 UTC, twilgenbus-ledger commented on src/main/scala/co/ledger/wallet/daemon/models/Pool.scala
> +          dbPrefix <- Try(config.getString("postgres.core.db_name_prefix"))
Nice catch!

2021-01-04 14:41 UTC, mbasire-ledger approved these changes

2021-01-05 20:05 UTC, mbasire-ledger commented on src/main/resources/application.conf.sample
> +}
where are the following configuration keys with their eventual env variables : 
 - redis.password
 - redis.db
 - redis.connection_timeout
?

The code redis backend implementation references those variables. By the way, there is no redis.name references in the preferences backend.

2021-01-05 20:51 UTC, twilgenbus-ledger commented on src/main/resources/application.conf.sample
> +}
```
redis.password
redis.db
redis.connection_timeout
```
Are all optional (see the pattern `Try().toOption` in the class `Pool`

Good catch on the redis.name. This is an artefact that should have been removed.

2021-01-05 21:54 UTC, RomanWlm commented on src/it/resources/application.conf
> +preferences {
`user-preferences` is probably a bit more accurate

2021-01-05 21:54 UTC, RomanWlm commented on src/main/resources/application.conf.sample
> +}
So, In order to be deployed and plugged on production existing redis instance, we would need to expose them into `application.conf.sample` with corresponding environment variables 
ie something like  : 
```
redis {
    host = "localhost"
    host = ${?REDIS_HOST}
    port = 6379
    port = ${?REDIS_PORT}
    password = ledger_secret
    password = ${REDIS_PASSWORD}
    db = default (?)
    db = ${REDIS_DB_NAME}
    connection_timeout = 2000 #ms ?
    connection_timeout = ${REDIS_CNX_TIMEOUT}
}
```

2021-01-05 21:54 UTC, RomanWlm commented on src/main/resources/application.conf.sample
> +preferences {
`user-preferences` is probably a bit more accurate
also what are accepted/possible values for this one (any other value will let us fallback on levelDb ?

2021-01-05 21:54 UTC, RomanWlm commented on src/main/scala/co/ledger/wallet/daemon/models/Pool.scala
> +      // else let libcore use leveldb
I think this is more safe to accept redis or leveldb but fail on any other values (avoid misconfiguration issues that will pass the deployment phase)

2021-01-05 21:54 UTC, RomanWlm commented on src/main/scala/co/ledger/wallet/daemon/models/Pool.scala
> +      // else let libcore use leveldb
Also, could we add a little Info log for preference storage configured on levelDb ? (The existing one for redis is already existing 👍 )

2021-01-05 21:54 UTC, RomanWlm commented on src/main/scala/co/ledger/wallet/daemon/models/Pool.scala
> +        info(s"Using Redis as core preference database $redisConfig")
Avoid to log redis db password :)

2021-01-05 21:54 UTC, RomanWlm commented on src/main/scala/co/ledger/wallet/daemon/models/Pool.scala
> +        info(s"Using Redis as core preference database $redisConfig")
copy(password = "****") can be fine here

2021-01-06 10:02 UTC, twilgenbus-ledger commented on src/main/resources/application.conf.sample
> +}
Agreed, a couple more precisions first:
- db: it's an integer, useful only in cluster mode (useful only if we were reach huge numbers of preferences and require >20Go) => it will most likely never be changed
- password: usage of a password in Redis is recommended only if the instance will be exposed to the internet (which is not what it was designed for, [more](https://redis.io/topics/security)) => it will most likely never be changed
- connection_timeout: redis just doesn't close clients connections by default for performance reasons. This is mostly useful in weird clients configuration (i.e: a rogue number of clients and/or connections) or a debug situation where a controlled client would have a bug. [more](https://redis.io/topics/clients) => it will most likely never be changed

I believe it would be better to just have the lines:
```
password = ${?REDIS_PASSWORD}
db = ${?REDIS_DB_NAME}
connection_timeout = ${?REDIS_CONNECTION_TIMEOUT}
```
And no defaults.

2021-01-06 10:03 UTC, twilgenbus-ledger commented on src/main/scala/co/ledger/wallet/daemon/models/Pool.scala
> +      // else let libcore use leveldb
Agreed on both ideas 👍

2021-01-06 10:08 UTC, twilgenbus-ledger commented on src/main/scala/co/ledger/wallet/daemon/models/Pool.scala
> +        info(s"Using Redis as core preference database $redisConfig")
Good catch!

2021-01-06 15:31 UTC, merged

2021-01-07 07:50 UTC, twilgenbus-ledger commented on src/main/resources/application.conf.sample
> +    connection_timeout = 2000
Yes 👍