Daemon doesn't need lama
LedgerHQ/ledger-wallet-daemon pull request #331
Opened 2021-01-21 10:03 UTC by twilgenbus-ledger

This PR provides optimisations on the NRT implementation:
- rewrite `AccountSynchronizer` to allow control over number of synchronisations running in parallel
     > Changed the paradigm of 1 account <-> 1 synchronizer. Now it is stateless (mostly) and converse with a new actor `AccountSynchronizerWatchdog` that keeps the state and acts as an communication interface with the `AccountSynchronizerManager` 
- remove leak in `HttpCoreClientPool`
- rewrite `AccountPublisher` to both:
     - take into account the new `AccountSynchronizer` (and removes the `OperationCount` system)
     - make use of the new libcore event `UPDATE_OPERATIONS` that allows batch reads on Postgres
- new libCore version that brings:
    - postgres connections are locked a lot less longer
    - batching new operations
    - better sync perfs (x6)
    - remove leak from http client
- add metrics about on going syncs

2021-01-22 15:22 UTC, RomanWlm requested changes

2021-01-22 15:22 UTC, RomanWlm commented on src/main/scala/co/ledger/wallet/daemon/services/AccountSynchronizer.scala
> +  def syncAllRegisteredAccounts(): Future[Seq[SynchronizationResult]] = {
Usefull for tests but to me not something we want on production...
Any idea to restric usage to tests only ?

2021-01-22 15:22 UTC, RomanWlm commented on src/main/scala/co/ledger/wallet/daemon/services/AccountSynchronizer.scala
> +  val accountsPublisherIndex: mutable.Map[ActorRef, AccountInfo] = new mutable.HashMap()
Is it thread safe ?

2021-01-22 15:22 UTC, RomanWlm commented on src/main/scala/co/ledger/wallet/daemon/services/AccountSynchronizer.scala
> +    // FIXME: this probably just OOM the process or steals all the CPU
Agree

2021-01-22 16:06 UTC, twilgenbus-ledger commented on src/it/scala/co/ledger/wallet/daemon/api/AccountsApiTest.scala
> +    assert(20 === utxoList.count)
This address actually belongs to @pollastri-pierre which is still using it seems.

2021-01-22 16:20 UTC, mbasire-ledger commented on src/main/scala/co/ledger/wallet/daemon/services/AccountSynchronizer.scala
> +  val accountsPublisherIndex: mutable.Map[ActorRef, AccountInfo] = new mutable.HashMap()
If all of these maps are modified in the thread of the Actor, yes, it is thread safe. But, if there are modified in a future or something like that, it is not.

2021-01-22 16:29 UTC, twilgenbus-ledger commented on src/main/scala/co/ledger/wallet/daemon/services/AccountSynchronizer.scala
> +  def syncAllRegisteredAccounts(): Future[Seq[SynchronizationResult]] = {
Agreed.
Frankly, I'd rather not have code we don't want in production at all. If we want it for tests, I think best would be to use a helper function to wipe the db (or a temporary db), and just start a sync anew. Best would be to just remove it for me.

2021-01-22 16:29 UTC, twilgenbus-ledger commented on src/main/scala/co/ledger/wallet/daemon/services/AccountSynchronizer.scala
> +  val accountsPublisherIndex: mutable.Map[ActorRef, AccountInfo] = new mutable.HashMap()
No. Luckily we're in an actor which appends to be mono threaded 😄

2021-01-22 16:33 UTC, twilgenbus-ledger commented on src/main/scala/co/ledger/wallet/daemon/services/AccountSynchronizer.scala
> +  val accountsPublisherIndex: mutable.Map[ActorRef, AccountInfo] = new mutable.HashMap()
@mbasire-ledger says it all.

2021-01-22 16:34 UTC, twilgenbus-ledger commented on src/main/scala/co/ledger/wallet/daemon/services/AccountSynchronizer.scala
> +    synchronizer = context.actorOf(Props(new AccountSynchronizer(self)).withMailbox("account-synchronizer-mailbox"), "synchronizer")
Not happy about this part, the [documentation advise against it](https://doc.akka.io/docs/akka/current/actors.html#dangerous-variants).

2021-01-22 16:54 UTC, twilgenbus-ledger commented on build-jar.sh
> +LIBCORE_VERSION="3.5.0-rc-d02e01"
Because the PR also comes with a libcore version that brings the following changes:
- postgres connections are locked a lot less longer
- batching new operations
- better sync perfs (x6)
- remove leak from http client

2021-01-22 16:55 UTC, twilgenbus-ledger commented on src/it/scala/co/ledger/wallet/daemon/services/AccountSynchronizerManagerTest.scala
> +/*  "AccountSynchronizerManager.start" should "register accounts and schedule a periodic registration" in {
Nope. But I'd like to write new ones but haven't had the time yet. Happy to pair start of next week to add some together if you want 👍

2021-01-22 16:56 UTC, twilgenbus-ledger commented on src/main/scala/co/ledger/wallet/daemon/services/AccountOperationsPublisher.scala
> +  case class UpdatedOperationsEvent(uids: Array[OperationId])
Excellent point.

2021-01-26 10:40 UTC, twilgenbus-ledger commented on src/it/scala/co/ledger/wallet/daemon/services/AccountSynchronizerManagerTest.scala
> +/*  "AccountSynchronizerManager.start" should "register accounts and schedule a periodic registration" in {
Tests fixed!

2021-01-26 10:40 UTC, twilgenbus-ledger commented on src/main/scala/co/ledger/wallet/daemon/services/AccountSynchronizer.scala
> +    synchronizer = context.actorOf(Props(new AccountSynchronizer(self)).withMailbox("account-synchronizer-mailbox"), "synchronizer")
Solved in latest commits

2021-02-02 13:24 UTC, RomanWlm approved these changes
Looks good to me ! 
When IT are passing, Let's go for RC 🚀

2021-02-02 14:52 UTC, merged