DD context logging
LedgerHQ/ledger-wallet-daemon pull request #362
Opened 2021-04-06 13:23 UTC by gagbo

Create a Datadog-specific, json-based logback configuration, and annotate logs accordingly throughout the application

2021-04-12 14:48 UTC, gagbo commented on build.sbt
> +  val logbackJsonVersion  = "6.2"
I updated logback from 1.1.7 to 1.2.3,  added logbackJsonVersion for logstash encoder.

2021-04-13 15:34 UTC, twilgenbus-ledger requested changes

2021-04-13 15:34 UTC, twilgenbus-ledger commented on src/main/scala/co/ledger/wallet/daemon/services/AccountSynchronizer.scala
> +      log.warning(
I don't think this should be moved to a warning

2021-04-13 15:35 UTC, twilgenbus-ledger commented
Thanks you, that'll be immensely useful.

2021-04-14 07:00 UTC, gagbo commented on src/it/resources/application.conf
> +    log-config-on-start = on
It’s not used anywhere, it’s an old artifact from @mbasire-ledger changes

2021-04-14 07:00 UTC, gagbo commented on src/main/resources/application.conf.sample
> +    log-config-on-start = on
It’s not used anywhere, it’s an old artifact from @mbasire-ledger changes

2021-04-14 07:00 UTC, gagbo commented on src/main/scala/co/ledger/wallet/daemon/services/AccountSynchronizer.scala
> +      log.warning(
Sure !

2021-04-16 08:38 UTC, twilgenbus-ledger approved these changes
LGTM!

2021-04-19 07:22 UTC, merged